services:
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=${CADDY_VERSION}
    restart: always
    networks:
      - ha_external
      - pihole_external
      - streaming_external
      - grafana_external
      - budget_external
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './config/Caddyfile:/etc/caddy/Caddyfile'
      - './data:/data'
      - './config:/config'
    environment:
      HOME_DOMAIN: '${HOME_DOMAIN}'
      PUID: ${PUID}
      PGID: ${PGID}
      CF_API_TOKEN: ${CF_API_TOKEN}
      DOMAIN: '${DOMAIN}'

networks:
  ha_external:
    external: true
  pihole_external:
    external: true
  streaming_external:
    external: true
  grafana_external:
    external: true
  budget_external:
    external: true
