services:
  caddy:
    container_name: caddy
    image: caddy
    restart: always
    networks:
      - ha_external
      - pihole_external
      - jellyfin_external
      - portainer_external
      - grafana_external
      - budget_external
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './config/Caddyfile:/etc/caddy/Caddyfile'
      - './data:/data'
      - './config:/config'
    environment:
      HOME_DOMAIN: '${HOME_DOMAIN}'
      PUID: ${PUID}
      PGID: ${PGID}

networks:
  ha_external:
    external: true
  pihole_external:
    external: true
  jellyfin_external:
    external: true
  portainer_external:
    external: true
  grafana_external:
    external: true
  budget_external:
    external: true
  
