services:
  plex:
    image: linuxserver/plex
    container_name: plex
    restart: unless-stopped
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "5353:5353/udp" 
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      # - "33400:33400" # If you use Plex Web Tools
    # devices:
    #   - /dev/dri:/dev/dri # for hardware transcoding
    env_file:
      - .env
    volumes:
      - './config:/config'
      - './data/tv:/tv'
      - './data/movies:/movies'
      - '/dev/shm:/transcode'
    environment:
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: 'http://${HOST_IP}:32400/'
      ALLOWED_NETWORKS: '${PLEX_ALLOWED_NETWORKS}'
      PUID: ${PUID}
      PGID: ${PGID}

networks:
  default:
    name: ${REVERSE_PROXY_NETWORK}
    external: true
