services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - './config/:/config'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
    ports:
      - '8123:8123'

networks:
  default:
    name: ${REVERSE_PROXY_NETWORK}
    external: true