services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    volumes:
      - './config/etc-pihole:/etc/pihole'
      - './config/etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD} 
      FTLCONF_LOCAL_IPV4: '${HOST_IP}'
      VIRTUAL_HOST: 'pihole.${HOME_DOMAIN}'
      PUID: ${PUID}
      PGID: ${PGID}
    extra_hosts:
      - '${HOME_DOMAIN}:${HOST_IP}'
      - 'pihole pihole.${HOME_DOMAIN}:${HOST_IP}'
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    restart: always

networks:
  default:
    name: ${REVERSE_PROXY_NETWORK}
    external: true
  