services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - grafana_internal
    security_opt:
      - no-new-privileges:true
    volumes:
      - './data:/var/lib/grafana'
      - './config:/etc/grafana'
    restart: unless-stopped
    user: "$PUID:$PGID"
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel"
      GF_SECURITY_ADMIN_PASSWORD: $GRAFANA_ADMIN_PASSWORD

networks:
  grafana_internal:
    name: grafana_internal
    internal: true
