services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config:/config
      - /dev/shm:/transcode
      - ${TV_MEDIA_PATH}:/tv
      - ${MOVIE_MEDIA_PATH}:/movies
    environment:
      - 'PLEX_CLAIM=${PLEX_CLAIM}'
      - 'ADVERTISE_IP=http://${HOST_IP}:32400,http://plex.${HOME_DOMAIN}'
      - ALLOWED_NETWORKS=${ALLOWED_NETWORKS}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    devices:
     - /dev/dri:/dev/dri
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${PUID}:${PGID}
    group_add:
      - "993"
    networks:
      - streaming_external
    volumes:
      - './config/jellyfin:/config'
      - './config/jellyfin/cache:/cache'
      - ${TV_MEDIA_PATH}:/media/tv
      - ${MOVIE_MEDIA_PATH}:/media/movies
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: 'unless-stopped'
    security_opt:
      - no-new-privileges:true
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.${HOME_DOMAIN}
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - './config/gluetun:/gluetun'
    ports:
      - 8080:8080 # Qbittorrent WebUI
    environment:
      TZ: $TZ
      PUID: ${PUID}
      PGID: ${PGID}
      FIREWALL_OUTBOUND_SUBNETS: ${ALLOWED_NETWORKS}
      # Wireguard
      VPN_SERVICE_PROVIDER: surfshark
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: $WG_VPN_PRIVATE_KEY
      WIREGUARD_ADDRESSES: 10.14.0.2/16
      # SERVER_REGIONS: ${VPN_REGIONS}
      SERVER_COUNTRIES: ${VPN_COUNTRIES}
      UPDATER_PERIOD: 24h
    networks:
      - streaming_external
    security_opt:
      - no-new-privileges:true
  qbit:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbit
    network_mode: "service:gluetun"
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - './config/qbit:/config'
      - ${QBIT_DOWNLOADS_PATH}:/data/downloads
      - ${QBIT_TORRENTS_PATH}:/data/torrents
      - ${TV_MEDIA_PATH}:/data/tv
      - ${MOVIE_MEDIA_PATH}:/data/movies
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: $TZ
      UMASK_SET: 002
    depends_on:
      - gluetun

networks:
  streaming_external:
    name: streaming_external
